name: Org Deploy

on:
  push:
    branches: [ 'org/**' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  org-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: npm install and npm run build
        run: |
          echo "Org: ${GITHUB_REF##*/}"
          echo "Current path: $(pwd)"
          ls -la
          npm ci --ignore-scripts
          # TODO: Change this to use org's config
          npm run build -- -c "production"

      - name: running unit tests
        run: npm run test:chromeheadless

      - uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: patient.${GITHUB_REF##*/}.pointmotioncontrol.com
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: /home/runner/work/sh_patient_client/sh_patient_client/dist/sh_patient_client
