name: Org Deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - 'org/**'

jobs:
  org-build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - uses: actions/checkout@v2

      - name: Debug GH branch names
        run: |
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "GITHUB_HEAD_REF##*/: ${GITHUB_HEAD_REF##*/}"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "Org: ${GITHUB_REF##*/}"

      - name: npm install and npm run build
        run: |
          echo "Org: ${GITHUB_REF##*/}"
          echo "Current path: $(pwd)"
          ls -la
          npm ci --ignore-scripts
          npm run build -- -c "${GITHUB_REF#*/*/}"

          # Create `version.json` file...
          echo "{\"version\":\"${GITHUB_HEAD_REF##*/}\",\"timestamp\":\"$(date +"%Y-%m-%dT%H:%M:%S%z")\"}" > cp version.json ./dist/sh-player-client/

          # Listing files...
          ls -la

          # Listing dist...
          ls -la dist


      - name: Printing app version
        run: |
          cat dist/activities/version.json | jq

      - name: running unit tests
        run: npm run test:chromeheadless

      - uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: patient.${GITHUB_REF##*/}.pointmotioncontrol.com
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: /home/runner/work/sh-player-client/sh-player-client/dist/sh-player-client
